# Generated by Django 3.0.1 on 2020-02-05 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesModel',
            new_name='Service',
        ),
    ]
