# Generated by Django 3.1.5 on 2021-01-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='to_be_filtered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
