# Generated by Django 3.1.5 on 2021-01-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200220_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, upload_to='services-icons'),
        ),
    ]
