# Generated by Django 3.1.5 on 2021-01-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20210111_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='filter',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='to_be_filtered',
            field=models.BooleanField(default=True),
        ),
    ]
