# Generated by Django 2.2.5 on 2020-02-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20200215_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
