# Generated by Django 3.0.1 on 2020-02-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='hosted_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
