# Generated by Django 2.2.5 on 2020-02-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200215_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
