# Generated by Django 2.2.5 on 2020-02-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='protfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='porfolio_images', to='portfolio.Portfolio'),
        ),
    ]
