# Generated by Django 2.2.5 on 2020-02-17 16:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20200216_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 17, 16, 50, 47, 99630, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
