# Generated by Django 3.1.5 on 2021-02-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_portfolio_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
